### ISSUE TITLE
Expanding comments fails

### ISSUE THREAD

**Issue by pbui** [Xyphyn/photon#11]
When clicking on nested comments that say "1 more" or "6 more", there is a spinner for loading, but the comments do not appear.

This can be reproduced here:

https://nu.lemdro.id/post/lemmy.world/2042527

On Firefox, the failure is silent.  However, on Chrome, the failure triggers a red alert at the bottom that says the fetch failed.

In the Chrome, dev console, I see the following:

![Screenshot from 2023-07-25 12-46-45](https://github.com/Xyphyn/photon/assets/3976244/525b319c-1307-455a-b3b1-954c0c74fdbe)

Following the stacktrace takes me to this:

![Screenshot from 2023-07-25 12-48-13](https://github.com/Xyphyn/photon/assets/3976244/799aa733-faa1-48e6-b136-031ca5442823)

**Comment by Xyphyn** [comment]
FYI: "stack"traces from the network tab are typically more helpful.

![image](https://github.com/Xyphyn/photon/assets/80978739/b158ecc2-3064-43c7-83e9-0413aceb51ad)

This is due to the fact that the URL is from lemmy.world, but fetching comments has it attempt to fetch from lemdro.id, where a post of that ID doesn't exist. I'll fix this by making it fetch from `$page.params.instance`.

**Comment by Xyphyn** [comment]
It no longer errors now, but sometimes no comments will appear, this is likely an API bug as the request is successful
