### ISSUE TITLE
Allow to mark post as read

### ISSUE THREAD

**Issue by TailyFair** [Xyphyn/photon#114]
**Is your feature request related to a problem? Please describe.**
I want quick way to hide posts I'm not interested in.

**Describe the solution you'd like**
Some quick to access `mark as read` button would be the ideal solution.

**Describe alternatives you've considered**
Right now I just open in separate tabs and close them quickly so backend would marked them as read. But it's very cumbersome.

**Additional context**
I see at least 2 possible approaches:

- Store marked posts in local storage
- Open them in background, so backend would mark them as read?

**Comment by TailyFair** [comment]
I think this button should be only visible only to those that have disabled "show read posts".

I think for those that enable this (me included) would want this to be more reachable, I was thinking maybe something like this?
![image](https://github.com/Xyphyn/photon/assets/27275873/2771c90a-554c-414d-9cd4-66e49d7aa35c)
Or to be more consistent with other cases (inbox read and etc):
![image](https://github.com/Xyphyn/photon/assets/27275873/911cd119-2752-47b7-bd6f-4aa609012148)

**Comment by mateohhh** [comment]
However you implement it, please make it so that people who have "Show Read Posts" enabled can still manually hide individual posts with a button option. Under the "..." button would be fine.

I don't want everything I've already read to be hidden from me by default where I have to go somewhere specific to find it, and I don't want to have to scroll past all the posts I'm not interested in and haven't opened or read either. Somehow despite all its other BS, Reddit managed to get this feature correct.
