### ISSUE TITLE
Add an option to block community and/or instance from the feed

### ISSUE THREAD

**Issue by Tywele** [Xyphyn/photon#225]
**Is your feature request related to a problem? Please describe.**
To block a community or instance I have to go there first.

**Describe the solution you'd like**
It would be nice to have an option to block a community or the instance the communtiy is hosted on in the 3 dot menu at the bottom of the post while viewing the post in the feed.

**Comment by 0xCmdrKeen** [comment]
I feel you on that, but damn, that menu is already quite long as it is. Adding two more options might make it exceed the screen size on some devices. 

![screenshot](https://github.com/Xyphyn/photon/assets/98132670/63d68042-4000-4278-9e37-8d658b9f84f0)

Maybe if the upvote/downvote entries were removed it would work, but I think they are necessary at least when you have "compact posts" turned on and "show voting buttons" turned off.

**Comment by Tywele** [comment]
What if you add a sub menu to that menu for less used actions?

**Comment by 0xCmdrKeen** [comment]
Sorry just realized I posted a screenshot for the wrong app. I think this is the menu you're talking about, right? 

![image](https://github.com/Xyphyn/photon/assets/98132670/6a6d23ad-d51c-4030-aead-550959da5431)

In that case, yeah, I would like to see those options there too.

**Comment by Tywele** [comment]
Yes that's the menu I meant

**Comment by 0xCmdrKeen** [comment]
I've been experimenting with this but it turns out not to be that simple. When I put the buttons at the bottom, it kinda looks awkward having three red buttons there:

<img width="939" alt="Screenshot" src="https://github.com/Xyphyn/photon/assets/98132670/2626bd83-e886-434b-98ca-28edf2277488">

I tried putting them in the top section but it feels kinda top heavy and unbalanced:

<img width="943" alt="Screenshot" src="https://github.com/Xyphyn/photon/assets/98132670/5ce02806-242f-47c8-8175-ad8af5b46949">

**Comment by 0xCmdrKeen** [comment]
Alright, I tried putting additional buttons in the creator section and that seems a little better (and it would make sense to also be able to block the poster), but then there isn't really a good place to put a block instance button. And I can't add the instance up there because it's not available in this context. 

<img width="833" alt="Screen Shot 2023-12-29 at 5 25 46 PM" src="https://github.com/Xyphyn/photon/assets/98132670/2d60fa02-36ca-419e-bbde-01339aa888b2">

**Comment by Xyphyn** [comment]
I think that looks good. I will add this tomorrow

The only change I would make is removing the "block" text.

I'm also fine with instance blocking not available there, as it's a less common action

**Comment by Tywele** [comment]
I think that's pretty good and a good compromise.

**Comment by 0xCmdrKeen** [comment]
@Xyphyn no need, I can send a PR since I already got it working.

Just need to clean up the code a little since I had to do some refactoring to make it work (currently the only `block()` function is inside the `CommunityCard` component and kinda tightly wired up there, so I extracted it into a helper module).

Up to you though. Just LMK what you prefer.

**Comment by Xyphyn** [comment]
Photon is overdue for a long day of moving helper functions out of components, I'll work on that

**Comment by Xyphyn** [comment]
How do you check if the community is already blocked or not? Because the Lemmy API is great, it tells us if creator is blocked but not the community. woohoo

**Comment by 0xCmdrKeen** [comment]
@Xyphyn `MyUserInfo` has an array of community blocks: https://join-lemmy.org/api/interfaces/MyUserInfo.html
It's part of `GetSiteResponse`: https://join-lemmy.org/api/interfaces/GetSiteResponse.html

Should be available in the `$site` store.

**Comment by Xyphyn** [comment]
For that I use $profile?.user instead of $site

**Comment by 0xCmdrKeen** [comment]
That doesn't have the list of community blocks though.

**Comment by Xyphyn** [comment]
As it's not a common action i don't want to put it in a common action menu, you can just go to the community to block it
