### ISSUE TITLE
[Feature Request] Paste images directly into the comment

### ISSUE THREAD

**Issue by Heus-Sueh** [Xyphyn/photon#234]
**Is your feature request related to a problem? Please describe.**
It's a feature that Reddit has where you can copy an image and paste it directly into the field without needing to upload or open the file menu
[Screencast from 2024-01-02 21-34-54.webm](https://github.com/Xyphyn/photon/assets/98482469/2efc0c7e-a9df-43fc-9866-3575ddc73db4)

**Comment by 0xCmdrKeen** [comment]
Yeah I'd like to see that feature too. Something similar to how Github does this would be nice, where the entire textarea turns into a drop zone when you drag an image over it.

**Comment by Krafting** [comment]
We should be also able to use CTRL+V on a comment or new post body with an image in the clipboard, just like on the official lemmy UI, it should detect the image and upload it! I always need to go back to the lemmy UI when I want to paste an image, because it is way easier...

**Comment by mazury** [comment]
Waiting for that as well

**Comment by mazury** [comment]
Ok I figured out how to do it but I'm not an svelte guy and frontend in general so have some problems. We just have to add 
paste event handler in form in Post component: `on:paste={event => handlePaste(event)}`
Get the file from `event.clipboardData?.files[0]` and just upload it like it's already done in `ImageUploadModal`. I could do it but I don't really know how to organize the code so that we don't duplicate the uploading logic. @Xyphyn any tips? I guess we need to extract that logic and move somewhere but where?

**Comment by Xyphyn** [comment]
added in v1.28.0

**Comment by mazury** [comment]
@Xyphyn  I checked that locally on main branch and it doesn't work for me. Not sure if you can use paste event in TextArea component? IDE  only suggests keydown, change, input and focus.

**Comment by mazury** [comment]
Oh wow, didn't know that. Ok indeed itworks now.
