### ISSUE TITLE
When creating a post when inside a community, the default community should be the one that we are currently in

### ISSUE THREAD

**Issue by gapetto** [Xyphyn/photon#259]
**Is your feature request related to a problem? Please describe.**
It looks that when I want to create a post the default community is the one last posted on. That's wrong.

**Describe the solution you'd like**
Default community should be the one we are currently in

**Comment by Xyphyn** [comment]
What photon version? It already seems to be working properly for me

**Comment by mazury** [comment]
Yes it looks like it's working for me now as well, idk why but for some reason it didnt work for a while for one of my communities. I didn't test that thouroughly though. Anway, I'm closing it now.

**Comment by mazury** [comment]
I think something is still wrong here though. I will test it more later to figure out if its a server of front and when the exact pattern but it definitely is not working for me

**Comment by CTalvio** [comment]
Definitely still happening.

**Comment by CTalvio** [comment]
[Kooha-2024-03-01-18-41-25.webm](https://github.com/Xyphyn/photon/assets/4365015/9ce77801-dccf-49ff-b8c8-137df62112c0)


Here is a video. It happens when you go to create a post after hopping between a couple communities. The autofilled community will be one of the ones you just visited, instead of the one you're currently on.

**Comment by Xyphyn** [comment]
i think it works now
