### ISSUE TITLE
Rounded border around post

### ISSUE THREAD

**Issue by blox814123** [Xyphyn/photon#327]
old.reddit.com has rounded borders on posts (color #369) with a subtle background color (#fafafa). I suggest this for photon for better discernment between post and the rest of the content, including comments.

![image](https://github.com/Xyphyn/photon/assets/83985490/a5e147d2-3335-40e5-97fc-c82e93cd9382)

**Comment by Xyphyn** [comment]
This look wouldn't work right in Photon's design system

**Comment by blox814123** [comment]
Ok. Another option to improve the structure would be to separate post content, crossposts and comment section with horizonal lines, like on new Reddit:

![image](https://github.com/Xyphyn/photon/assets/83985490/c46e7b0a-38ce-40df-8118-227788e2f89b)

vs

![image](https://github.com/Xyphyn/photon/assets/83985490/1ac7a0ca-9f08-4c5c-b8f6-09c45adea54b)

**Comment by sevonj** [comment]
The crosspost list could also be condensed a bit, which might make it clearer.

<details>
  <summary>I played around a bit with inspect element</summary>

Current:
![photon-crosspost](https://github.com/Xyphyn/photon/assets/100710152/816513a0-9f79-47c4-99e5-c2b8d9c2fc94)

The URL is a bit redundant here, maybe we can do without:
![photon-crosspost-nourl](https://github.com/Xyphyn/photon/assets/100710152/afe82007-7a79-47fc-863c-d8613937570c)


No URL, compacted:
![photon-crosspost-compact](https://github.com/Xyphyn/photon/assets/100710152/8cec5101-a599-42d7-a469-6181045e4762)

</details>

The last one isn't ideal for narrow screens, but maybe it's OK to truncate titles, since we already know what the post is about.

**Comment by blox814123** [comment]
Also "crossposts" should be collapsed by default. Who wants to see a large list of crossposts? Not many probably. People go to posts for the comments.

**Comment by Xyphyn** [comment]
Please move the cross post design into a new issue.
