### ISSUE TITLE
Bug: Profile menu jumps when scrolling

### ISSUE THREAD

**Issue by sevonj** [Xyphyn/photon#389]
**Describe the bug**
The navbar profile menu is affected by scrolling and struggles to keep its position.

**To Reproduce** (if applicable)
- Leave the menu open
- Scroll up and down intensely 

**Expected behavior**
- The menu stays in place.

**Screenshots**

https://github.com/user-attachments/assets/77cb2ec2-d837-43c4-816b-cc4d2372c016

**Versions**
- Browser: Firefox, Chromium
- Photon version: 1.31.2

**Comment by Xyphyn** [comment]
The reason this is happening is because I recently made the floating-ui use a better positioning method that stops it from getting caught behind other elements, at the cost of having to recalculate the position, leading to this. It's basically up to: do you want no jumping, or do you want the menu to always be visible?

**Comment by sevonj** [comment]
> caught behind other elements

Like what?

Guess it'll be wontfix, then
